baseURL = 'https://0xNathanW.github.io/'
languageCode = 'en-gb'
title = 'Nathan W Blog'
theme = 'typo'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]

description = 'Blog description'

# Appearance
theme = 'light'
colorPalette = 'gruvebox'
hideHeader = false

# Intro on main page, content is markdown
# homeIntroTitle = 'Hi!'
homeIntroContent = """
Things that interest me.
"""

# Collection to display on home page, after intro.
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
# Number of posts per page.
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "github"
url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"